sudo: required
language: generic

services:
- docker

before_script:
- curl -sSLf https://get.docker.com | sed s/sleep\ 20/sleep\ 0/g | sudo -E sh

script:
  - make build
  - make build_samples
  - ./test/version.sh ./faas-cli

after_success:
    - if [ ! -z "$TRAVIS_TAG" ] ; then
        if [ -z "$DOCKER_NS" ] ; then
          export DOCKER_NS=openfaas;
        fi;

        docker tag $DOCKER_NS/faas-cli:latest-dev $DOCKER_NS/faas-cli:$TRAVIS_TAG;
        docker tag $DOCKER_NS/faas-cli:latest-dev $DOCKER_NS/faas-cli:latest;
        docker tag $DOCKER_NS/faas-cli:latest-dev-root $DOCKER_NS/faas-cli:${TRAVIS_TAG}-root;
        docker tag $DOCKER_NS/faas-cli:latest-dev-root $DOCKER_NS/faas-cli:latest-root;
        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
        docker push $DOCKER_NS/faas-cli:$TRAVIS_TAG;
        docker push $DOCKER_NS/faas-cli:latest;
        docker push $DOCKER_NS/faas-cli:${TRAVIS_TAG}-root;
        docker push $DOCKER_NS/faas-cli:latest-root;

        docker tag $DOCKER_NS/faas-cli:latest-dev quay.io/$DOCKER_NS/faas-cli:$TRAVIS_TAG;
        docker tag $DOCKER_NS/faas-cli:latest-dev quay.io/$DOCKER_NS/faas-cli:latest;
        docker tag $DOCKER_NS/faas-cli:latest-dev-root quay.io/$DOCKER_NS/faas-cli:${TRAVIS_TAG}latest-root;
        docker tag $DOCKER_NS/faas-cli:latest-dev-root quay.io/$DOCKER_NS/faas-cli:latest-root;
        echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
        docker push quay.io/$DOCKER_NS/faas-cli:$TRAVIS_TAG;
        docker push quay.io/$DOCKER_NS/faas-cli:latest;
        docker push quay.io/$DOCKER_NS/faas-cli:${TRAVIS_TAG}-root;
        docker push quay.io/$DOCKER_NS/faas-cli:latest-root;

      fi;

before_deploy:
  - make build_redist
  - make test-templating
  - ./ci/hashgen.sh

deploy:
  provider: releases
  api_key:
    secure: IBajIsnHa28g85gif5zp1hW/H0k85dMlYNs7QreEDoXMbGRhd7Ths6dKuilANkN6i42R5Z2vvuQVSNmkI/s4rA3c3v6T+Ng2NRo8l2dbnC75g56uTjo8qipBL05DWu79xDLcbZT9x/sxcLJAhBDa4ktf5yxQdcFTMumNjRR/ag/GllvOLa5pNETzSheCWnOXvD4QP/8gHXF6ISqhtn6lxEgogFYJE94eu3s9R0LcaZlatJX3XpTevOfjhcrf5QrURkILHuLgyw++VaJvTppeVn7BLMydufRX9bs7IsjscU8td8RZgnhrCOKmxnnrG9rznOcpJDwOYA3OElbOdGyNocAX79aKEyUiiWWIdbeMGbYUOLG2nNZeZXM1NeEnstIAss+QN5tl5egODqtE9tpiGJFK03U4lntkV6q2ZSvXyADBV9/edbVuTP4AnUNaHwjn9WPuW2zBsYx1o9FctVFvbJCsK5HwQnlU6Rsq8yVpw/1Hu/ySdSE0e3w8Q1mar4oGWezjbKpDXume0WeVmXGPyK8q6TVRsL/bZGU/8wHYg88tRyTmPT+Spza3GzovvplY+PZuBz+DkuLchdM2752uBeMkfV8sSdX4KNmahnGLzc/m8CRb+O9tC9qLuwjv52s1pqnbcKW3UFZE1bHw4MgIKBkiAKFD6ZRq5db6+lxJo6s=
  file:
  - faas-cli
  - faas-cli-darwin
  - faas-cli-armhf
  - faas-cli.exe
  - faas-cli-arm64
  - faas-cli.sha256
  - faas-cli-darwin.sha256
  - faas-cli-armhf.sha256
  - faas-cli.exe.sha256
  - faas-cli-arm64.sha256
  skip_cleanup: true
  on:
    tags: true

env:
  - GO111MODULE=off
